import * as jspb from 'google-protobuf'



export enum Status { 
  STATUS_UNKNOWN = 0,
  STATUS_PENDING = 1,
  STATUS_DOWNLOADING = 2,
  STATUS_ANALYSING = 3,
  STATUS_ANALYZED = 4,
  STATUS_TRANSCODING = 5,
  STATUS_TRANSCODED = 6,
  STATUS_MUXING = 7,
  STATUS_FINISHED = 8,
  STATUS_CANCELLED = 9,
  STATUS_FAILED = 10,
}
