// source: arranger/jobs/models.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var arranger_presets_models_pb = require('../../arranger/presets/models_pb.js');
goog.object.extend(proto, arranger_presets_models_pb);
var arranger_jobs_enums_pb = require('../../arranger/jobs/enums_pb.js');
goog.object.extend(proto, arranger_jobs_enums_pb);
var scheduler_models_pb = require('../../scheduler/models_pb.js');
goog.object.extend(proto, scheduler_models_pb);
goog.exportSymbol('proto.jobs.api.v1.Job', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jobs.api.v1.Job = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jobs.api.v1.Job.repeatedFields_, null);
};
goog.inherits(proto.jobs.api.v1.Job, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jobs.api.v1.Job.displayName = 'proto.jobs.api.v1.Job';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jobs.api.v1.Job.repeatedFields_ = [9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jobs.api.v1.Job.prototype.toObject = function(opt_includeInstance) {
  return proto.jobs.api.v1.Job.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jobs.api.v1.Job} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jobs.api.v1.Job.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    ownerId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    progress: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    status: jspb.Message.getFieldWithDefault(msg, 5, 0),
    inputInfo: (f = msg.getInputInfo()) && scheduler_models_pb.InputInfo.toObject(includeInstance, f),
    outputInfo: (f = msg.getOutputInfo()) && scheduler_models_pb.OutputInfo.toObject(includeInstance, f),
    resultInfosList: jspb.Message.toObjectList(msg.getResultInfosList(),
    scheduler_models_pb.ResultInfo.toObject, includeInstance),
    createdAt: jspb.Message.getFieldWithDefault(msg, 10, 0),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 11, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jobs.api.v1.Job}
 */
proto.jobs.api.v1.Job.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jobs.api.v1.Job;
  return proto.jobs.api.v1.Job.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jobs.api.v1.Job} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jobs.api.v1.Job}
 */
proto.jobs.api.v1.Job.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnerId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setProgress(value);
      break;
    case 5:
      var value = /** @type {!proto.jobs.api.v1.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 7:
      var value = new scheduler_models_pb.InputInfo;
      reader.readMessage(value,scheduler_models_pb.InputInfo.deserializeBinaryFromReader);
      msg.setInputInfo(value);
      break;
    case 8:
      var value = new scheduler_models_pb.OutputInfo;
      reader.readMessage(value,scheduler_models_pb.OutputInfo.deserializeBinaryFromReader);
      msg.setOutputInfo(value);
      break;
    case 9:
      var value = new scheduler_models_pb.ResultInfo;
      reader.readMessage(value,scheduler_models_pb.ResultInfo.deserializeBinaryFromReader);
      msg.addResultInfos(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedAt(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jobs.api.v1.Job.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jobs.api.v1.Job.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jobs.api.v1.Job} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jobs.api.v1.Job.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOwnerId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getProgress();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getInputInfo();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      scheduler_models_pb.InputInfo.serializeBinaryToWriter
    );
  }
  f = message.getOutputInfo();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      scheduler_models_pb.OutputInfo.serializeBinaryToWriter
    );
  }
  f = message.getResultInfosList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      scheduler_models_pb.ResultInfo.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = message.getUpdatedAt();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.jobs.api.v1.Job.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jobs.api.v1.Job} returns this
 */
proto.jobs.api.v1.Job.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string owner_id = 2;
 * @return {string}
 */
proto.jobs.api.v1.Job.prototype.getOwnerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.jobs.api.v1.Job} returns this
 */
proto.jobs.api.v1.Job.prototype.setOwnerId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.jobs.api.v1.Job.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.jobs.api.v1.Job} returns this
 */
proto.jobs.api.v1.Job.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional float progress = 4;
 * @return {number}
 */
proto.jobs.api.v1.Job.prototype.getProgress = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jobs.api.v1.Job} returns this
 */
proto.jobs.api.v1.Job.prototype.setProgress = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional Status status = 5;
 * @return {!proto.jobs.api.v1.Status}
 */
proto.jobs.api.v1.Job.prototype.getStatus = function() {
  return /** @type {!proto.jobs.api.v1.Status} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.jobs.api.v1.Status} value
 * @return {!proto.jobs.api.v1.Job} returns this
 */
proto.jobs.api.v1.Job.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional scheduler.api.v1.InputInfo input_info = 7;
 * @return {?proto.scheduler.api.v1.InputInfo}
 */
proto.jobs.api.v1.Job.prototype.getInputInfo = function() {
  return /** @type{?proto.scheduler.api.v1.InputInfo} */ (
    jspb.Message.getWrapperField(this, scheduler_models_pb.InputInfo, 7));
};


/**
 * @param {?proto.scheduler.api.v1.InputInfo|undefined} value
 * @return {!proto.jobs.api.v1.Job} returns this
*/
proto.jobs.api.v1.Job.prototype.setInputInfo = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jobs.api.v1.Job} returns this
 */
proto.jobs.api.v1.Job.prototype.clearInputInfo = function() {
  return this.setInputInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jobs.api.v1.Job.prototype.hasInputInfo = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional scheduler.api.v1.OutputInfo output_info = 8;
 * @return {?proto.scheduler.api.v1.OutputInfo}
 */
proto.jobs.api.v1.Job.prototype.getOutputInfo = function() {
  return /** @type{?proto.scheduler.api.v1.OutputInfo} */ (
    jspb.Message.getWrapperField(this, scheduler_models_pb.OutputInfo, 8));
};


/**
 * @param {?proto.scheduler.api.v1.OutputInfo|undefined} value
 * @return {!proto.jobs.api.v1.Job} returns this
*/
proto.jobs.api.v1.Job.prototype.setOutputInfo = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jobs.api.v1.Job} returns this
 */
proto.jobs.api.v1.Job.prototype.clearOutputInfo = function() {
  return this.setOutputInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jobs.api.v1.Job.prototype.hasOutputInfo = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated scheduler.api.v1.ResultInfo result_infos = 9;
 * @return {!Array<!proto.scheduler.api.v1.ResultInfo>}
 */
proto.jobs.api.v1.Job.prototype.getResultInfosList = function() {
  return /** @type{!Array<!proto.scheduler.api.v1.ResultInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, scheduler_models_pb.ResultInfo, 9));
};


/**
 * @param {!Array<!proto.scheduler.api.v1.ResultInfo>} value
 * @return {!proto.jobs.api.v1.Job} returns this
*/
proto.jobs.api.v1.Job.prototype.setResultInfosList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.scheduler.api.v1.ResultInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.scheduler.api.v1.ResultInfo}
 */
proto.jobs.api.v1.Job.prototype.addResultInfos = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.scheduler.api.v1.ResultInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jobs.api.v1.Job} returns this
 */
proto.jobs.api.v1.Job.prototype.clearResultInfosList = function() {
  return this.setResultInfosList([]);
};


/**
 * optional int64 created_at = 10;
 * @return {number}
 */
proto.jobs.api.v1.Job.prototype.getCreatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.jobs.api.v1.Job} returns this
 */
proto.jobs.api.v1.Job.prototype.setCreatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int64 updated_at = 11;
 * @return {number}
 */
proto.jobs.api.v1.Job.prototype.getUpdatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.jobs.api.v1.Job} returns this
 */
proto.jobs.api.v1.Job.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


goog.object.extend(exports, proto.jobs.api.v1);
