/* eslint-disable */
// source: prober/service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var prober_models_pb = require('../prober/models_pb.js');
goog.object.extend(proto, prober_models_pb);
var cloud_models_pb = require('../cloud/models_pb.js');
goog.object.extend(proto, cloud_models_pb);
var error_models_pb = require('../error/models_pb.js');
goog.object.extend(proto, error_models_pb);
goog.exportSymbol('proto.prober.api.v1.ProbeRequest', null, global);
goog.exportSymbol('proto.prober.api.v1.ProbeResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.prober.api.v1.ProbeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.prober.api.v1.ProbeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.prober.api.v1.ProbeRequest.displayName = 'proto.prober.api.v1.ProbeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.prober.api.v1.ProbeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.prober.api.v1.ProbeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.prober.api.v1.ProbeResponse.displayName = 'proto.prober.api.v1.ProbeResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.prober.api.v1.ProbeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.prober.api.v1.ProbeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.prober.api.v1.ProbeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.prober.api.v1.ProbeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    inputInfo: (f = msg.getInputInfo()) && prober_models_pb.InputInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.prober.api.v1.ProbeRequest}
 */
proto.prober.api.v1.ProbeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.prober.api.v1.ProbeRequest;
  return proto.prober.api.v1.ProbeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.prober.api.v1.ProbeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.prober.api.v1.ProbeRequest}
 */
proto.prober.api.v1.ProbeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new prober_models_pb.InputInfo;
      reader.readMessage(value,prober_models_pb.InputInfo.deserializeBinaryFromReader);
      msg.setInputInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.prober.api.v1.ProbeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.prober.api.v1.ProbeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.prober.api.v1.ProbeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.prober.api.v1.ProbeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInputInfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      prober_models_pb.InputInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional InputInfo input_info = 1;
 * @return {?proto.prober.api.v1.InputInfo}
 */
proto.prober.api.v1.ProbeRequest.prototype.getInputInfo = function() {
  return /** @type{?proto.prober.api.v1.InputInfo} */ (
    jspb.Message.getWrapperField(this, prober_models_pb.InputInfo, 1));
};


/**
 * @param {?proto.prober.api.v1.InputInfo|undefined} value
 * @return {!proto.prober.api.v1.ProbeRequest} returns this
*/
proto.prober.api.v1.ProbeRequest.prototype.setInputInfo = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.prober.api.v1.ProbeRequest} returns this
 */
proto.prober.api.v1.ProbeRequest.prototype.clearInputInfo = function() {
  return this.setInputInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.prober.api.v1.ProbeRequest.prototype.hasInputInfo = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.prober.api.v1.ProbeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.prober.api.v1.ProbeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.prober.api.v1.ProbeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.prober.api.v1.ProbeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileInfo: (f = msg.getFileInfo()) && prober_models_pb.FileInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.prober.api.v1.ProbeResponse}
 */
proto.prober.api.v1.ProbeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.prober.api.v1.ProbeResponse;
  return proto.prober.api.v1.ProbeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.prober.api.v1.ProbeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.prober.api.v1.ProbeResponse}
 */
proto.prober.api.v1.ProbeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new prober_models_pb.FileInfo;
      reader.readMessage(value,prober_models_pb.FileInfo.deserializeBinaryFromReader);
      msg.setFileInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.prober.api.v1.ProbeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.prober.api.v1.ProbeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.prober.api.v1.ProbeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.prober.api.v1.ProbeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileInfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      prober_models_pb.FileInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional FileInfo file_info = 2;
 * @return {?proto.prober.api.v1.FileInfo}
 */
proto.prober.api.v1.ProbeResponse.prototype.getFileInfo = function() {
  return /** @type{?proto.prober.api.v1.FileInfo} */ (
    jspb.Message.getWrapperField(this, prober_models_pb.FileInfo, 2));
};


/**
 * @param {?proto.prober.api.v1.FileInfo|undefined} value
 * @return {!proto.prober.api.v1.ProbeResponse} returns this
*/
proto.prober.api.v1.ProbeResponse.prototype.setFileInfo = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.prober.api.v1.ProbeResponse} returns this
 */
proto.prober.api.v1.ProbeResponse.prototype.clearFileInfo = function() {
  return this.setFileInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.prober.api.v1.ProbeResponse.prototype.hasFileInfo = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.prober.api.v1);
